export { CustomerAnalyticsPage } from './Analytics/Analytics'
export { CreateProjectPage } from './CreateProject/CreateProject'
export { ProjectsPage } from './Projects/Projects'
export { ProjectDetailPage } from './ProjectDetail/ProjectDetail'
export { CustomerReviewPage } from './Review/CustomerReviewPage'
