# Generated by Django 4.2.30 on 2026-04-21 17:50

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                ("dataset_id", models.BigIntegerField(primary_key=True, serialize=False, verbose_name="dataset_id")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("domain", models.CharField(max_length=255, verbose_name="domain")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created_at")),
            ],
        ),
        migrations.CreateModel(
            name="PlatformUser",
            fields=[
                ("user_id", models.BigIntegerField(primary_key=True, serialize=False, verbose_name="user_id")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="email")),
                (
                    "role",
                    models.CharField(
                        choices=[("STUDENT", "Student"), ("ADMIN", "Admin")],
                        default="STUDENT",
                        max_length=10,
                        verbose_name="role",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="time")),
                ("is_active", models.BooleanField(default=True, verbose_name="is_active")),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("task_id", models.BigIntegerField(primary_key=True, serialize=False, verbose_name="task_id")),
                ("image", models.CharField(max_length=500)),
                (
                    "current_stage",
                    models.CharField(
                        choices=[("ANNOTATION", "Annotation"), ("VERIFICATION", "Verification"), ("REVIEW", "Review")],
                        default="ANNOTATION",
                        max_length=20,
                        verbose_name="current_stage",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "In Queue"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="QUEUED",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created_at")),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_dataset",
                        to="app.dataset",
                        verbose_name="dataset",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dataset",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dataset_user",
                to="app.platformuser",
                verbose_name="owner",
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("audit_id", models.BigIntegerField(primary_key=True, serialize=False, verbose_name="audit_id")),
                ("action", models.CharField(max_length=255, verbose_name="action")),
                ("timestamp", models.DateTimeField(auto_now_add=True, verbose_name="timestamp")),
                ("ip_address", models.GenericIPAddressField(verbose_name="ip_address")),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_task",
                        to="app.task",
                        verbose_name="task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_user",
                        to="app.platformuser",
                        verbose_name="user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "assignment_id",
                    models.BigIntegerField(primary_key=True, serialize=False, verbose_name="assignment_id"),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[("ANNOTATION", "Annotation"), ("VERIFICATION", "Verification"), ("REVIEW", "Review")],
                        default="ANNOTATION",
                        max_length=20,
                        verbose_name="stage",
                    ),
                ),
                ("annotation", models.JSONField(blank=True, default=dict, verbose_name="annotation")),
                ("started_at", models.DateTimeField(auto_now_add=True, verbose_name="started_at")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="completed_at")),
                (
                    "verdict",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("APPROVED", "Approved"), ("REJECTED", "Rejected")],
                        default="PENDING",
                        max_length=20,
                        verbose_name="verdict",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_task",
                        to="app.task",
                        verbose_name="task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_user",
                        to="app.platformuser",
                        verbose_name="user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdminUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email address")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
