# Generated by Django 4.2.30 on 2026-05-25 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("app", "0002_task_annotation_task_status"),
        ("app", "0003_pool_next_pool_pool_pool_type"),
        ("app", "0004_remove_pool_is_active_remove_pool_next_pool_and_more"),
    ]

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="annotation",
            field=models.JSONField(blank=True, default=list, null=True, verbose_name="annotation"),
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("AVAILABLE", "Available"), ("COMPLETED", "Completed")],
                default="AVAILABLE",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="pool_type",
            field=models.CharField(
                choices=[
                    ("ANNOTATION", "Annotation"),
                    ("VERIFICATION", "Verification"),
                    ("CLASSIFICATION", "Classification"),
                ],
                default="ANNOTATION",
                max_length=50,
            ),
        ),
        migrations.RemoveField(
            model_name="pool",
            name="is_active",
        ),
        migrations.AddField(
            model_name="pool",
            name="order",
            field=models.IntegerField(default=1, verbose_name="order"),
        ),
        migrations.AddField(
            model_name="pool",
            name="status",
            field=models.CharField(
                choices=[("OPEN", "Open"), ("COMPLETED", "Completed")], default="OPEN", max_length=50
            ),
        ),
        migrations.CreateModel(
            name="Pipeline",
            fields=[
                ("pipeline_id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="pipline_id")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("limit", models.IntegerField(blank=True, null=True, verbose_name="limit")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created_at")),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pipline_dataset",
                        to="app.dataset",
                        verbose_name="dataset",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipline_user",
                        to="app.platformuser",
                        verbose_name="user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pool",
            name="pipeline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pool_pipline",
                to="app.pipeline",
                verbose_name="pipline",
            ),
        ),
    ]
