# Generated by Django 4.2.30 on 2026-05-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="annotation",
            field=models.JSONField(default=list, verbose_name="annotation"),
        ),
    ]
