# Generated by Django 4.2.30 on 2026-06-03 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("app", "0005_alter_assignment_annotation"),
        ("app", "0006_assignment_pool"),
        ("app", "0007_alter_pool_pipeline"),
        ("app", "0008_pool_target_institution"),
        ("app", "0009_pool_tasks_limit"),
        ("app", "0010_alter_assignment_status"),
        ("app", "0011_assignment_expires_at_pool_time_limit"),
        ("app", "0012_task_height_task_width"),
    ]

    dependencies = [
        ("app", "0002_task_annotation_task_status_squashed_0004_remove_pool_is_active_remove_pool_next_pool_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="annotation",
            field=models.JSONField(blank=True, default=None, null=True, verbose_name="annotation"),
        ),
        migrations.AddField(
            model_name="assignment",
            name="pool",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignment_pool",
                to="app.pool",
            ),
        ),
        migrations.AlterField(
            model_name="pool",
            name="pipeline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pool_pipeline",
                to="app.pipeline",
                verbose_name="pipline",
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="target_institution",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="target_institution"),
        ),
        migrations.AddField(
            model_name="pool",
            name="tasks_limit",
            field=models.IntegerField(default=10, verbose_name="tasks_limit"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", "In Progress"),
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("ARCHIVED", "Archived"),
                ],
                default="IN_PROGRESS",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pool",
            name="time_limit",
            field=models.IntegerField(default=600, verbose_name="time_limit"),
        ),
        migrations.AddField(
            model_name="task",
            name="height",
            field=models.IntegerField(default=1080),
        ),
        migrations.AddField(
            model_name="task",
            name="width",
            field=models.IntegerField(default=1920),
        ),
    ]
