# Generated by Django 4.2.30 on 2026-05-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_task_annotation_task_status_squashed_0004_remove_pool_is_active_remove_pool_next_pool_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="annotation",
            field=models.JSONField(blank=True, default=None, null=True, verbose_name="annotation"),
        ),
    ]
