# Generated by Django 4.2.30 on 2026-05-26 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_assignment_annotation"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="pool",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignment_pool",
                to="app.pool",
            ),
        ),
    ]
