# Generated by Django 4.2.30 on 2026-05-26 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_assignment_pool"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pool",
            name="pipeline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pool_pipeline",
                to="app.pipeline",
                verbose_name="pipline",
            ),
        ),
    ]
