# Generated by Django 4.2.30 on 2026-05-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_pool_pipeline"),
    ]

    operations = [
        migrations.AddField(
            model_name="pool",
            name="target_institution",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="target_institution"),
        ),
    ]
