# Generated by Django 4.2.30 on 2026-05-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_pool_target_institution"),
    ]

    operations = [
        migrations.AddField(
            model_name="pool",
            name="tasks_limit",
            field=models.IntegerField(default=10, verbose_name="tasks_limit"),
        ),
    ]
