# Generated by Django 4.2.30 on 2026-06-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_pool_tasks_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", "In Progress"),
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("ARCHIVED", "Archived"),
                ],
                default="IN_PROGRESS",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
