# Generated by Django 4.2.30 on 2026-06-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_assignment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pool",
            name="time_limit",
            field=models.IntegerField(default=600, verbose_name="time_limit"),
        ),
    ]
