# Generated by Django 4.2.30 on 2026-06-04 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_assignment_annotation_squashed_0012_task_height_task_width"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformuser",
            name="role",
            field=models.CharField(
                choices=[("STUDENT", "Student"), ("CUSTOMER", "Customer"), ("ADMIN", "Admin")],
                default="STUDENT",
                max_length=10,
                verbose_name="role",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="height",
            field=models.IntegerField(default=1080, verbose_name="height"),
        ),
        migrations.AlterField(
            model_name="task",
            name="width",
            field=models.IntegerField(default=1920, verbose_name="width"),
        ),
        migrations.CreateModel(
            name="IssuedToken",
            fields=[
                ("jti", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked", models.BooleanField(default=False)),
                ("device_id", models.UUIDField(unique=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_tokens",
                        to="app.platformuser",
                    ),
                ),
            ],
        ),
    ]
