# Generated by Django 4.2.30 on 2026-06-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_alter_platformuser_role_alter_task_height_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformuser",
            name="password",
            field=models.CharField(default=9, max_length=128),
            preserve_default=False,
        ),
    ]
